### ISSUE TITLE
Automated tests

### ISSUE THREAD

**Issue by akohli96** [batflyer/boostsrl-python-package#1]
Unit tests can be written for this package to ensure all features are fully function.
[UnitTest](https://docs.python.org/2/library/unittest.html)

**Comment by batflyer** [comment]
@akohli96 Setting this issue to closed.

Travis continuous integration badge was added to the [README](https://github.com/batflyer/boostsrl-python-package/blob/master/README.md), current and future unit tests will be in the `tests/` directory (refer specifically [tests.py](https://github.com/batflyer/boostsrl-python-package/blob/master/tests/tests.py) and [requirements.txt](https://github.com/batflyer/boostsrl-python-package/blob/master/tests/requirements.txt)).

The current testing implementation requires the `boostsrl` directory to exist in two places (because of the jar's reliance on files being located in specific places). I'm adding Issue #2 as an issue introduced through this one's resolution.

I will continue adding unit tests as features and syntax are designed. If this is not to satisfaction, feel free to submit another issue or send a pull request.

**Comment by akohli96** [comment]
Thank you @batflyer just wanted to bring up automated testing to your attention. Glad to know my suggestion came in handy.
